// <auto-generated />
namespace PhotoAlbum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_required_to_UserFileName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_required_to_UserFileName));
        
        string IMigrationMetadata.Id
        {
            get { return "201705030359330_added_required_to_UserFileName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
